spring.application.name=online-library

spring.datasource.url=jdbc:mysql://localhost:3306/online_library?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

server.port=8080
